worker_processes auto;

events {
    worker_connections 1024;
}

http {
    upstream wildfly_backend {
        # Use Docker Compose service names
        server wildfly1:8080;
        server wildfly2:8080;
        server wildfly3:8080;

        # JSESSIONID-based stickiness
        # sticky name=JSESSIONID expires=1h path=/; NAO FUNCIONOU

        # Optionally, enable session stickiness (recommended for JSF apps)
        hash $remote_addr consistent; # IP hash for basic stickiness
    }

    server {
        listen 80;
        server_name localhost; # Or your domain name

        location / {
            proxy_pass http://wildfly_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 600;
            proxy_send_timeout 600;
            proxy_read_timeout 600;
        }

        # Optionally, location for static files if you want Nginx to serve them directly
        # location ~* \.(jpg|jpeg|gif|png|css|js|ico|xml)$ {
        #     root /usr/share/nginx/html; # Example path
        #     expires 30d;
        # }
    }
}